((lambda (a b . x)
    ((lambda (c d . y)
        ((lambda (e f . z)
            ((lambda (g h)
                ((lambda (h i . hn)
                    ((lambda (j k . gg)
                        ((lambda (l m . sds)
                            ((lambda (n o . dffds)
                                ((lambda (p q . fsdf)
                                    ((lambda (r s . dsfd)
                                        ((lambda (t u . sdfds)
                                            ((lambda (v w . zzz)
                                                ((lambda (x y z . gsgs) p) 1 2 3 4 6))4 5 5 4))6 7 5))8 9 4))10 11 44))12 13 4))14 15 53))16 17 44))18 19))20 21))22 23))24 25))26 27 31)
; produces ApplicTP
