((lambda (a b)
    ((lambda (c d)
        ((lambda (e f)
            ((lambda (g h)
                ((lambda (h i)
                    ((lambda (j k)
                        ((lambda (l m)
                            ((lambda (n o)
                                ((lambda (p q)
                                    ((lambda (r s)
                                        ((lambda (t u)
                                            ((lambda (v w)
                                                ((lambda (x y z) b) 1 2 3))4 5))6 7))8 9))10 11))12 13))14 15))16 17))18 19))20 21))22 23))24 25))26 27)
((lambda (a b)
    ((lambda (c d)
        ((lambda (e f)
            ((lambda (g h)
                ((lambda (h i)
                    ((lambda (j k)
                        ((lambda (l m)
                            ((lambda (n o)
                                ((lambda (p q)
                                    ((lambda (r s)
                                        ((lambda (t u)
                                            ((lambda (v w)
                                                ((lambda (x y z) k) 1 2 3))4 5))6 7))8 9))10 11))12 13))14 15))16 17))18 19))20 21))22 23))24 25))26 27)